### ISSUE TITLE
Error during buildout

### ISSUE THREAD

**Issue by marfago** [collective/collective.z3cform.colorpicker#1]
When executing the buildout I get this error:

Getting distribution for 'collective.z3cform.colorpicker>=1.1'.
error: [Errno 2] No such file or directory: 'README.txt'
An error occurred when trying to install collective.z3cform.colorpicker 1.2. Look above this message for any errors that were output by easy_install.
While:
  Installing instance.
  Getting distribution for 'collective.z3cform.colorpicker>=1.1'.
Error: Couldn't install: collective.z3cform.colorpicker 1.2

Backporting to version 1.1 works fine.

**Comment by kaerumy** [comment]
symlinks doesn't work for eggs for buildout, it works as source checkout though

**Comment by ramiroluz** [comment]
The package from pypi have a zero sized README.txt.

https://pypi.python.org/packages/source/c/collective.z3cform.colorpicker/collective.z3cform.colorpicker-1.2.tar.gz

**Comment by ramiroluz** [comment]
@kaerumy it works as source checkout because in the repository the README.txt is correct.

**Comment by reinhardt** [comment]
+1

**Comment by msom** [comment]
+1

**Comment by mauritsvanrees** [comment]
I fixed this on 31 August, but this needs a new release.
@gborelli Can you make a release one of these day? Thanks.

**Comment by gborelli** [comment]
Done - https://pypi.python.org/pypi/collective.z3cform.colorpicker/1.3

**Comment by reinhardt** [comment]
Yup, that's better. Thank you, guys!
